//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PqnLesson10ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pqnkhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pqnkhoa()
        {
            this.pqnsinhvien = new HashSet<pqnsinhvien>();
        }
    
        public string PqnMaKH { get; set; }
        public string PqnTenKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pqnsinhvien> pqnsinhvien { get; set; }
    }
}
