//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PqnLesson10ASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PqnK22CNTT1lesson10Entities : DbContext
    {
        public PqnK22CNTT1lesson10Entities()
            : base("name=PqnK22CNTT1lesson10Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pqnketqua> pqnketqua { get; set; }
        public virtual DbSet<pqnkhoa> pqnkhoa { get; set; }
        public virtual DbSet<pqnmonhoc> pqnmonhoc { get; set; }
        public virtual DbSet<pqnsinhvien> pqnsinhvien { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
