//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PqnLesson10ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pqnsinhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pqnsinhvien()
        {
            this.pqnketqua = new HashSet<pqnketqua>();
        }
    
        public string PqnMaSV { get; set; }
        public string PqnHoSV { get; set; }
        public string PqnTenSV { get; set; }
        public Nullable<bool> PqnPhai { get; set; }
        public Nullable<System.DateTime> PqnNgaySinh { get; set; }
        public string PqnNoiSinh { get; set; }
        public string PqnMaKH { get; set; }
        public string PqnHocBong { get; set; }
        public string PqnDiemTrungBinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pqnketqua> pqnketqua { get; set; }
        public virtual pqnkhoa pqnkhoa { get; set; }
    }
}
